// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// INAR1_cpp
NumericVector INAR1_cpp(NumericVector resid, double a);
RcppExport SEXP _INAr_INAR1_cpp(SEXP residSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(INAR1_cpp(resid, a));
    return rcpp_result_gen;
END_RCPP
}
// INARp_cpp
NumericVector INARp_cpp(NumericVector resid, DoubleVector a);
RcppExport SEXP _INAr_INARp_cpp(SEXP residSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(INARp_cpp(resid, a));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_genINARmarg
IntegerVector rcpp_genINARmarg(double a, IntegerVector Xseries, IntegerVector resid);
RcppExport SEXP _INAr_rcpp_genINARmarg(SEXP aSEXP, SEXP XseriesSEXP, SEXP residSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Xseries(XseriesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type resid(residSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_genINARmarg(a, Xseries, resid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_INAr_INAR1_cpp", (DL_FUNC) &_INAr_INAR1_cpp, 2},
    {"_INAr_INARp_cpp", (DL_FUNC) &_INAr_INARp_cpp, 2},
    {"_INAr_rcpp_genINARmarg", (DL_FUNC) &_INAr_rcpp_genINARmarg, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_INAr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
