# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

series_varpv <- function(mu, alpha, max_j = 2000L) {
    .Call('_INAr_series_varpv', PACKAGE = 'INAr', mu, alpha, max_j)
}

#' Sun-McCabe score statistic to test for dependence in an integer autoregressive process
#' @param x NumericVector
#' @param method unsigned int
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
SMC_Cpp <- function(x, method) {
    .Call('_INAr_SMC_Cpp', PACKAGE = 'INAr', x, method)
}

#' Semiparametric bootstrap version of the Sun-McCabe score test.
#' @param x NumericVector
#' @param B int
#' @param method unsigned int
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
SMC_semiparBOOT_Cpp <- function(x, B, method) {
    .Call('_INAr_SMC_semiparBOOT_Cpp', PACKAGE = 'INAr', x, B, method)
}

#' Parametric bootstrap version of the Sun-McCabe score test.
#' @param x NumericVector
#' @param B int
#' @param method unsigned int
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
SMC_parBOOT_Cpp <- function(x, B, method) {
    .Call('_INAr_SMC_parBOOT_Cpp', PACKAGE = 'INAr', x, B, method)
}

#' PIT bootstrap version of the Sun-McCabe score test.
#' @param x NumericVector
#' @param B int
#' @param method unsigned int
#' @details
#' This is an internal function, it will be excluded in future versions.
#' !!!!! DA IMPLEMENTARE !!!!!
#' @noRd
SMC_pitBOOT_Cpp <- function(x, B, method) {
    .Call('_INAr_SMC_pitBOOT_Cpp', PACKAGE = 'INAr', x, B, method)
}

#' Sort and remove duplicates from a numeric vector
#' @param v NumericVector
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
sortunique <- function(v) {
    .Call('_INAr_sortunique', PACKAGE = 'INAr', v)
}

#' Compute the empirical cumulative distribution function of a numeric vector
#' @param eval NumericVector
#' @param x NumericVector
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
ecdfcpp <- function(eval, x) {
    .Call('_INAr_ecdfcpp', PACKAGE = 'INAr', eval, x)
}

#' Harris-McCabe score statistic to test for dependence in an integer autoregressive process
#' @param x NumericVector
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
HMC_Cpp <- function(x) {
    .Call('_INAr_HMC_Cpp', PACKAGE = 'INAr', x)
}

#' Bootstrap version of the Harris-McCabe score test.
#' @param x NumericVector
#' @param B int
#' @details
#' This is an internal function, it will be excluded in future versions.
#' @noRd
HMC_BOOT_Cpp <- function(x, B) {
    .Call('_INAr_HMC_BOOT_Cpp', PACKAGE = 'INAr', x, B)
}

YW_cpp <- function(r) {
    .Call('_INAr_YW_cpp', PACKAGE = 'INAr', r)
}

INARp_cpp <- function(resid, a) {
    .Call('_INAr_INARp_cpp', PACKAGE = 'INAr', resid, a)
}

#' Generate a MINAR(p) series
#'
#' Experimental function
#'
#' @param resid Numeric matrix of size n x m, where n is the number of time points and m is the number of series.
#' @param A Numeric matrix of size m x m*p, where m is the number of series. Each column of A contains the autoregressive parameters for the corresponding lag.
#' @details
#' This is an internal function.
MINARp_gen_cpp <- function(resid, A) {
    .Call('_INAr_MINARp_gen_cpp', PACKAGE = 'INAr', resid, A)
}

Xresid <- function(X, alphas, mINN, vINN) {
    .Call('_INAr_Xresid', PACKAGE = 'INAr', X, alphas, mINN, vINN)
}

Xmoments <- function(X, alphas) {
    .Call('_INAr_Xmoments', PACKAGE = 'INAr', X, alphas)
}

inar1_poi_loglik_cpp <- function(x, alpha, lambda) {
    .Call('_INAr_inar1_poi_loglik_cpp', PACKAGE = 'INAr', x, alpha, lambda)
}

saddle_nll_cpp <- function(x, alpha, lambda) {
    .Call('_INAr_saddle_nll_cpp', PACKAGE = 'INAr', x, alpha, lambda)
}

